---
abstract: 'Makes fork() in debugger to open a new Tmux window'
author:
  - 'L<Peter Vereshagin|http://vereshagin.org> <peter@vereshagin.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Sort::Versions: 0
  Sub::Name: 0
  Test::Exception: 0
  Test::More: 0.94
  Test::Most: 0
  Test::Strict: 0
  Test::Version: 1.002
  autodie: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debug-Fork-Tmux
no_index:
  directory:
    - inc
requires:
  Carp: 0
  Config: 0
  Const::Fast: 0
  Cwd: 0
  Env::Path: 0
  File::Basename: 0
  File::Spec: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://bugs.vereshagin.org/product/Debug-Fork-Tmux
  repository: https://github.com/petr999/Debug-Fork-Tmux.git
version: 1.000012
